// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPResources
{
        public const string achievement_apprentice = "CgkIw_PP7OYOEAIQBQ"; // <GPGSID>
        public const string achievement_curious = "CgkIw_PP7OYOEAIQGA"; // <GPGSID>
        public const string achievement_thanks_for_playing = "CgkIw_PP7OYOEAIQGw"; // <GPGSID>
        public const string achievement_40_challenges = "CgkIw_PP7OYOEAIQDQ"; // <GPGSID>
        public const string achievement_genius = "CgkIw_PP7OYOEAIQAw"; // <GPGSID>
        public const string achievement_piece_of_cake = "CgkIw_PP7OYOEAIQDw"; // <GPGSID>
        public const string achievement_30_challenges = "CgkIw_PP7OYOEAIQDA"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkIw_PP7OYOEAIQEA"; // <GPGSID>
        public const string achievement_30_skins = "CgkIw_PP7OYOEAIQFA"; // <GPGSID>
        public const string achievement_banking = "CgkIw_PP7OYOEAIQGg"; // <GPGSID>
        public const string achievement_learning_the_ropes = "CgkIw_PP7OYOEAIQAg"; // <GPGSID>
        public const string achievement_challenger = "CgkIw_PP7OYOEAIQCQ"; // <GPGSID>
        public const string achievement_20_challenges = "CgkIw_PP7OYOEAIQCw"; // <GPGSID>
        public const string achievement_got_lucky = "CgkIw_PP7OYOEAIQEQ"; // <GPGSID>
        public const string achievement_beginner = "CgkIw_PP7OYOEAIQBA"; // <GPGSID>
        public const string achievement_expert = "CgkIw_PP7OYOEAIQBg"; // <GPGSID>
        public const string achievement_40_skins = "CgkIw_PP7OYOEAIQFQ"; // <GPGSID>
        public const string achievement_grand_master = "CgkIw_PP7OYOEAIQCA"; // <GPGSID>
        public const string achievement_its_easy = "CgkIw_PP7OYOEAIQAQ"; // <GPGSID>
        public const string achievement_10_skins = "CgkIw_PP7OYOEAIQEg"; // <GPGSID>
        public const string achievement_20_skins = "CgkIw_PP7OYOEAIQEw"; // <GPGSID>
        public const string achievement_master = "CgkIw_PP7OYOEAIQBw"; // <GPGSID>
        public const string achievement_10_challenges = "CgkIw_PP7OYOEAIQCg"; // <GPGSID>
        public const string achievement_reskinning = "CgkIw_PP7OYOEAIQGQ"; // <GPGSID>
        public const string achievement_50_skins = "CgkIw_PP7OYOEAIQFg"; // <GPGSID>
        public const string achievement_high_roller = "CgkIw_PP7OYOEAIQFw"; // <GPGSID>
        public const string achievement_50_challenges = "CgkIw_PP7OYOEAIQDg"; // <GPGSID>

}

